function mostrarSeleccionado(){

    if(document.getElementById("Nequi").checked){

            location.href = "Nequi.Html"

    }

    if(document.getElementById("Pse").checked){

        location.href = "Pse.Html"

    }

    if(document.getElementById("MasterCard").checked){

        location.href = "MasterCard.Html"

    }

    if(document.getElementById("Visa").checked){

        location.href = "Visa.Html"

    }

}